### ISSUE TITLE
Is it possible to generate WaveformData from Node.js?

### ISSUE THREAD

**Issue by bitwit** [bbcrd/waveform-data.js#33]
I believe that the short answer to this questions is "no" given that the webaudio builder uses the AudioContext object from the browser.
However, maybe a 'nodebuilder' plugin could be created/PR'd that uses a different method to perform the `decodeAudioData()` function and complete the process, or that's what I'm thinking anyway.

For example, I found a WIP node web audio project here: https://github.com/sebpiq/node-web-audio-api , though I'm a bit iffy on its semi-complete status.

In any case I wanted to inquire here first before going on a fork adventure since I'm sure BBCRD understands waveform data better than I do.

**Comment by bitwit** [comment]
Closing issue as it probably fits best in some sort of a fork or plugin and not in the `dist` build. We've chosen to take a different path and won't have the time to build it though.

I'm sure it's a low priority too considering the C++ Waveform library, but I still would contest there's a place for a node builder module that could possible mask some of the complexity involved in setting up and using the C++ Waveform library directly.

Cheers

**Comment by oncletom** [comment]
A good option would be to use the C++ waveform library as a Node native binding to avoid reimplementing all the logic.

Otherwise, it is about decoding an audio buffer and extracting some values. But it is a project by itself, and even the WebAudio decoder should probably be separated out from this project.
